version: "3"

services:
  node:
    image: node:16
    container_name: investments_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: db
      JWT_SECRET: ${JWT_SECRET}
  db:
    container_name: investments_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

networks:
  default:
    name: investments_api_net